name: Github Metrics
on:
  # Schedule daily updates
  schedule: 
    - cron: "* * * * *" 
  push: 
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          config_display: large
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "chore: Update ${filename}"
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_limit: 0
          
